openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Students
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://superhero-backend-vrcc.onrender.com
paths:
  /superhero:
    get:
      $ref: '../swagger/paths/superhero/get.yaml'
    post:
      $ref: '../swagger/paths/superhero/post.yaml'
  /superhero/{id}:
    get:
      $ref: '../swagger/paths/superhero/{id}/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
